### ISSUE TITLE
Better feedback on SD screen

### ISSUE THREAD

**Issue by shadowninja108** [shadowninja108/HACGUI#4]

**Comment by shadowninja108** [comment]
Idea being to add checkmarks to indicate to the user what still needs to be done.

**Comment by KuestenKeks** [comment]
do you mean the screen titled "instructions" and showing the following?

> 
> 1. Run hekate on your Switch
> 2. Navigate to...
> ...

I'm a little bit confused here.. I did all that prior to downloading HACGUI. I can't continue now as the "Next" button is disabled and I have no idea why.

**Comment by KuestenKeks** [comment]
I've had a quick look at the source code and realized, that HACGUI actually wait's for an sd card to be inserted that has the correct folder structure and all the backup files created with Hekate.

I think you should allow the user to choose the path to those files.

I had saved them on my hard drive. To get around this issue I took another sd card, created the required folder structure and copied everything onto the sd card. It was a little bit of a hassle ^^
But I realize that your way is very comfortable when everything is still saved on the sd card and the sd card is readily available. But that might not always be the case.

Now I'm waiting for my raw NAND backup to finish to proceed. Anyway, thanks for providing this tool in the first place ;)

**Edit:** it worked! Now I finally have all the keys in my %userprofile%\\.switch\ folder and ChoiDujour won't complain anymore. Thanks! :)

**Comment by shadowninja108** [comment]
Yea, I've definitely need to add more flexibility in the setup process. A few things I plan on doing:

-Manually specify BOOT0, SBK, and TSEC keys
-Feedback for when SD is plugged in
-Display what is missing from the SD card if anything
-Add a "Restart as Admin" button to NAND page if not running as admin
-Add error detection to prevent random crashes (already finished)

**Comment by shadowninja108** [comment]
All have been implemented locally. Hoping to have a release soon.

**Comment by shadowninja108** [comment]
Fixed in latest release :)
