### ISSUE TITLE
Crash when deriving keys with latest Switch firmware (6.2.0)

### ISSUE THREAD

**Issue by legoj15** [shadowninja108/HACGUI#6]
When presented with the SD card instructions, clicking next shows the "Deriving keys..." screen, but then abruptly closes
![image](https://user-images.githubusercontent.com/7399802/49982745-4a00a400-ff2c-11e8-9721-5529f4cd48a4.png)

**Comment by shadowninja108** [comment]
This issue has been fixed locally, but I'm preparing other features before I make a release.

**Comment by chardido** [comment]
I've the same problem too!

The support of 6.2.0 is already a great feature :)

**Comment by Akechii** [comment]
please fix it asap

**Comment by shadowninja108** [comment]
Trying to get a new release out ASAP. There's been a lot of changes and things need to be cleaned up.

**Comment by shadowninja108** [comment]
Fixed in latest release :)
