### ISSUE TITLE
Error while decrypting keys on 6.2.0

### ISSUE THREAD

**Issue by ZzzDave** [shadowninja108/HACGUI#7]
System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.IO.InvalidDataException: Failed to decrypt package2! Is the correct key present?
à LibHac.Package2.FindKeyGeneration(Keyset keyset, IStorage storage)
à LibHac.Package2..ctor(Keyset keyset, IStorage storage)
à HACGUI.FirstStart.PickNANDPage.OnNandFound() dans B:\Documents\Switch_Projects\hactoolgui\hactoolgui\FirstStart\PickNANDPage.xaml.cs:ligne 119
à HACGUI.FirstStart.PickNANDPage.<StartDeriving>b__2_1(DerivingPage page) dans B:\Documents\Switch_Projects\hactoolgui\hactoolgui\FirstStart\PickNANDPage.xaml.cs:ligne 91
à HACGUI.FirstStart.DerivingPage.<>c__DisplayClass0_0.<.ctor>b__1() dans B:\Documents\Switch_Projects\hactoolgui\hactoolgui\FirstStart\DerivingPage.xaml.cs:ligne 24
à System.Threading.Tasks.Task.Execute()
--- Fin de la trace de la pile d'exception interne ---
---> (Exception interne #0) System.IO.InvalidDataException: Failed to decrypt package2! Is the correct key present?
à LibHac.Package2.FindKeyGeneration(Keyset keyset, IStorage storage)
à LibHac.Package2..ctor(Keyset keyset, IStorage storage)
à HACGUI.FirstStart.PickNANDPage.OnNandFound() dans B:\Documents\Switch_Projects\hactoolgui\hactoolgui\FirstStart\PickNANDPage.xaml.cs:ligne 119
à HACGUI.FirstStart.PickNANDPage.<StartDeriving>b__2_1(DerivingPage page) dans B:\Documents\Switch_Projects\hactoolgui\hactoolgui\FirstStart\PickNANDPage.xaml.cs:ligne 91
à HACGUI.FirstStart.DerivingPage.<>c__DisplayClass0_0.<.ctor>b__1() dans B:\Documents\Switch_Projects\hactoolgui\hactoolgui\FirstStart\DerivingPage.xaml.cs:ligne 24
à System.Threading.Tasks.Task.Execute()<---

**Comment by shadowninja108** [comment]
Try deleting the entire /backups folder on your SD card, then redumping the relevant things

**Comment by ZzzDave** [comment]
No, still getting the same error. (My switch can only boot in rcm maybe it's a cause?)

**Comment by shadowninja108** [comment]
Your package2 image on your NAND is likely corrupted then.

**Comment by ZzzDave** [comment]
so what can I do? Buy a new switch?? :/

**Comment by shadowninja108** [comment]
Generate a correct copy with Choidujournx and write it to your NAND

**Comment by ZzzDave** [comment]
But to use ChoiDuJourNX I need to boot up my switch to launch Homebrew Launcher and I can't, I tried to downgrade it to 1.0.0 but now cfw doesn't work

**Comment by shadowninja108** [comment]
Oh my mistake, I mean ChoiDujour

**Comment by ZzzDave** [comment]
Uh don't I need prod.keys to use ChoiDuJour?

**Comment by DaveSwitch** [comment]
And anyway when I search for "ChoiDuJour tutorial" it just gives me ChoiDuJourNX tutorials

**Comment by ZzzDave** [comment]
How can I generate a new package2 image with ChoiDuJour?

**Comment by shadowninja108** [comment]
BCPKG2-1-Normal-Main would be package2. You would need to write it to your NAND via etcher or hekate (maybe?). As for the keys needed by ChoiDuJour, you'll need to find them somewhere.

**Comment by ZzzDave** [comment]
But if I restore BCPKG2-1-Normal-Main I could get the keys from hacgui right?

**Comment by shadowninja108** [comment]
Correct

**Comment by ZzzDave** [comment]
I tried to backup only BCPKG2-1-Normal-Main Restore but it didn't worked so I will do a full gpp restore then retry.

**Comment by ZzzDave** [comment]
So I did the gpp restore but can't extract, but i found the keys.txt on google, how can I use ChoiDuJour to upgrade?

**Comment by shadowninja108** [comment]
https://gbatemp.net/threads/how-to-install-run-any-switch-firmware-unofficially-without-burning-any-fuses.507461/

**Comment by ZzzDave** [comment]
Are Keys.txt console unique? because I got error because a key is "Not Confirmed"

**Comment by shadowninja108** [comment]
Are you on the Kosmos or ReSwitched Discord server? It might be better to move to the support channels of one of those.

**Comment by ZzzDave** [comment]
Yeah I will thx
