### ISSUE TITLE
Oops! Something went wrong... 7.0.1 after plugging in switch with memloader

### ISSUE THREAD

**Issue by ghost** [shadowninja108/HACGUI#9]
I built it myself, is 7.X support ready yet?
https://pastebin.com/22Cy4esx
Also, is there a way to put in my own keys file? I want to try the NAND/SD viewer.
Thank you for your work on this software.

**Comment by ghost** [comment]
Still not working on latest commit

**Comment by shadowninja108** [comment]
If you restart the setup(delete something in ~/.switch) it will prompt you to import keys from Lockpick_RCM (or whatever else). As for importing keys in general, I’m considering adding a key viewer.

**Comment by ghost** [comment]
Still errors after connecting nand.

**Comment by shadowninja108** [comment]
Oh my mistake, I fixed a small issue locally but didn't push it.
https://github.com/shadowninja108/HACGUI/blob/63644b65b6048ccf32f6ba2fff863c4fdcf4bb47/hactoolgui/Main/MainPage.xaml.cs#L39-L41
Until I push it, wrap this section with
`Dispatcher.Invoke(() => 
{
// code
})`

**Comment by ghost** [comment]
It seems that the restart to run as admin for memloader causes the error, when I run as admin directly the error does not happen and the keys are derived.

**Comment by shadowninja108** [comment]
Mind posting the stacktrace?

**Comment by ghost** [comment]
I cloned the repo again, I get this https://pastebin.com/xbzEQUR8 after plugging in the switch if I click the restart as admin button, and if I start as admin there is no error. I did not see your comment before, I'll try that next.

**Comment by shadowninja108** [comment]
Might be a untested issue, I’ll test it myself when I can.

**Comment by ghost** [comment]
I can get the keys derived, but every time I open the application it puts me back in the first launch screen, even though the data is in the hacgui folder inside the .switch folder. Am I missing something?

**Comment by shadowninja108** [comment]
I've pushed two commits that may fix or help troubleshoot your issues. One changes how restart as admin works during the setup (untested), and the other will tell you what it thinks is invalid about your install.

**Comment by shadowninja108** [comment]
Make that 3 commits (I forgot something)

**Comment by ghost** [comment]
Thank you, the newest commits solved the restart to admin, but when I restart I get 'Console "tickets" does not have a client certificate.' If I change out the error check, I get a console.keys does not exist, but it exists in the folder.
Edit: not comment out invert it

**Comment by shadowninja108** [comment]
Hm, go to `%userprofile%/.switch/HACGUI/consoles.`
Delete any empty folders

**Comment by LiamMCW** [comment]
-

**Comment by ghost** [comment]
under C:\Users\Liam\.switch\HACGUI\console there is no empty folders, just my new MyConsole folder and the tickets folder.
Edit: .switch/hacgui/consoles does not exist, just .switch/hacgui/console, which has myConsole and tickets.

**Comment by shadowninja108** [comment]
![image](https://user-images.githubusercontent.com/13044396/55131286-393efd00-50db-11e9-99c3-731b3fcdcc4d.png)
This is what an example console directory should look like. I don't know how the program could skip creating the certificate?

**Comment by ghost** [comment]
The certificate is in there, along with the tickets and the console keys. I'm away from my computer right now so I can't test.

**Comment by shadowninja108** [comment]
I had a look at the certificate dumping code and noticed a ~~really stupid~~ bug that may have caused issues. I cleaned up the code in the latest commit and fixed the issue. See if it works now.

**Comment by ghost** [comment]
I think it thinks that the tickets folder is a console. 
![image](https://user-images.githubusercontent.com/35670972/55195100-ebc99b00-5181-11e9-8130-1ab0ae7b121d.png)
![image](https://user-images.githubusercontent.com/35670972/55195142-13206800-5182-11e9-80bc-901fcd1e7469.png)
It creates a tickets folder here every time I run.
If I delete the folder, I can get past this and I can access the other features of the app.

**Comment by shadowninja108** [comment]
That’s likely why, but I don’t see why that would occur? I guess I’ll have a look. Do you know exactly when it occurs?

**Comment by ghost** [comment]
When what occurs? The ticket folder creation? That happens at the end when all the keys are shown.

**Comment by shadowninja108** [comment]
Yes, that folder should be in the console’s folder.

**Comment by LiamMCW** [comment]
`C:.
│   console.keys
│   extra.keys
│   prod.keys
│   title.keys
│
└───HACGUI
    │   preferences.ini
    │
    └───console
        ├───TestConsole
        │   │   console.keys
        │   │   nx_tls_client_cert.pfx
        │   │
        │   └───tickets
        │           01000000000100000000000000000003.tik
        │           01000000000108000000000000000004.tik
        │           01001520000228000000000000000003.tik
        │           01001520000228000000000000000004.tik
        │           010025400aece0000000000000000005.tik
        │           01003a400c3da0000000000000000005.tik
        │           01003a400c3da8000000000000000007.tik
        │           01003bc0000a00000000000000000000.tik
        │           01003bc0000a08000000000000000003.tik
        │           010040600c5ce0000000000000000007.tik
        │           010040600c5ce8000000000000000008.tik
        │           01005d100807a0000000000000000004.tik
        │           01005d100807a8000000000000000004.tik
        │           01006a800016e0000000000000000005.tik
        │           01006a800016e8000000000000000007.tik
        │           01007ef00011e0000000000000000000.tik
        │           01007ef00011e8000000000000000003.tik
        │           01007ef00011f0010000000000000000.tik
        │           01007ef00011f0020000000000000000.tik
        │           0100d870045b60000000000000000005.tik
        │           0100d870045b68000000000000000005.tik
        │           0100d870045b68000000000000000007.tik
        │
        └───tickets
                01000000000100000000000000000003.tik
                01000000000108000000000000000004.tik
                01001520000228000000000000000003.tik
                01001520000228000000000000000004.tik
                010025400aece0000000000000000005.tik
                01003a400c3da0000000000000000005.tik
                01003a400c3da8000000000000000007.tik
                01003bc0000a00000000000000000000.tik
                01003bc0000a08000000000000000003.tik
                010040600c5ce0000000000000000007.tik
                010040600c5ce8000000000000000008.tik
                01005d100807a0000000000000000004.tik
                01005d100807a8000000000000000004.tik
                01006a800016e0000000000000000005.tik
                01006a800016e8000000000000000007.tik
                01007ef00011e0000000000000000000.tik
                01007ef00011e8000000000000000003.tik
                01007ef00011f0010000000000000000.tik
                01007ef00011f0020000000000000000.tik
                0100d870045b60000000000000000005.tik
                0100d870045b68000000000000000005.tik
                0100d870045b68000000000000000007.tik`

**Comment by ghost** [comment]
https://ghostbin.com/paste/v4ofx
These are the folders I have after deleting everything but prod.keys and starting from scratch. It seems to think the extra tickets folder which was created for some reason is a console.
![image](https://user-images.githubusercontent.com/35670972/55199671-3ef71a00-5191-11e9-9173-dbae8cd48043.png)

**Comment by ghost** [comment]
Because I can access the main menu and dump games after deleting the extra tickets folder, I think my issue is solved. If you want me to do more testing, please tell me.
